<?php

/*
 * This file is part of the 'fpdf2-make-font-ui' package.
 *
 * For the license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author bibi.nu <bibi@bibi.nu>
 */

declare(strict_types=1);

namespace App\Service;

use Twig\Attribute\AsTwigFunction;

/**
 * Service to generate a nonce value.
 */
class NonceService
{
    /**
     *  The generated nonce.
     */
    private ?string $nonce = null;

    /**
     * @param positive-int $length the length of generated bytes
     */
    public function __construct(private readonly int $length = 16)
    {
    }

    /**
     * Gets the CSP nonce.
     *
     * @param positive-int|null $length the length of generated bytes
     */
    #[AsTwigFunction(name: 'csp_nonce')]
    public function getCspNonce(?int $length = null): string
    {
        return \sprintf("'nonce-%s'", $this->getNonce($length));
    }

    /**
     * Generates a random nonce value.
     *
     * @param positive-int|null $length the length of generated bytes
     */
    public function getNonce(?int $length = null): string
    {
        if (null === $this->nonce) {
            $this->nonce = \bin2hex(\openssl_random_pseudo_bytes($length ?? $this->length));
        }

        return $this->nonce;
    }
}
