<?php

/*
 * This file is part of the 'fpdf2-make-font-ui' package.
 *
 * For the license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author bibi.nu <bibi@bibi.nu>
 */

declare(strict_types=1);

namespace App\Twig;

use App\Service\NonceService;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

/**
 * Extension to generate a random CSP nonce value.
 */
final class NonceExtension extends AbstractExtension
{
    public function __construct(private readonly NonceService $service)
    {
    }

    /**
     * @throws \Exception
     */
    #[\Override]
    public function getFunctions(): array
    {
        return [
            new TwigFunction('csp_nonce', $this->getNonce(...)),
        ];
    }

    /**
     * Generates a random nonce value.
     *
     * @param positive-int|null $length the length of generated bytes
     */
    public function getNonce(?int $length = null): string
    {
        return $this->service->getNonce($length);
    }
}
