framework:
    asset_mapper:
        paths:
            - assets/
        missing_import_mode: strict
        importmap_polyfill: false
        importmap_script_attributes:
            crossorigin: 'anonymous'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
