framework:
    secret: '%env(APP_SECRET)%'
    session: true

    default_locale: en
    enabled_locales: ['en', 'fr']

    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
