php_version: 8.2
global_exclude_dirs:
    - tests
    - var
    - vendor
    - vendor-bin
exclude_patterns:
    - config/reference.php
rules:
    web.apache_config:
        enabled: false
    twig.xss_vulnerability:
        enabled: false
