php_version: 8.2
global_exclude_dirs:
    - vendor
    - tests
rules:
    php.class_too_long:
        enabled: false
    php.use_exit_function:
        enabled: true
        ignore_files:
            - src/makeFont.php
